package lcm

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestWriteMemoryFile_BasicOutput(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	memories := []ExtractedMemory{
		{Type: MemoryFact, Content: "The project uses SQLite via sqlc", Confidence: 0.95},
		{Type: MemoryDecision, Content: "Chose sha256 for ID generation", Confidence: 0.9},
	}

	n, err := WriteMemoryFile(context.Background(), memories, dir, MemoryFileConfig{})
	require.NoError(t, err)
	require.Greater(t, n, 0)

	data, err := os.ReadFile(filepath.Join(dir, "CRUSH.memory.md"))
	require.NoError(t, err)
	content := string(data)

	require.Contains(t, content, "# Session Memory")
	require.Contains(t, content, "<!-- auto-generated by Crush -->")
	require.Contains(t, content, "**[fact]** The project uses SQLite via sqlc")
	require.Contains(t, content, "**[decision]** Chose sha256 for ID generation")
}

func TestWriteMemoryFile_LineLimitEnforced(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	var memories []ExtractedMemory
	for i := range 250 {
		memories = append(memories, ExtractedMemory{
			Type:       MemoryFact,
			Content:    "item " + itoa(i),
			Confidence: 0.9,
		})
	}

	n, err := WriteMemoryFile(context.Background(), memories, dir, MemoryFileConfig{MaxLines: 50})
	require.NoError(t, err)
	require.Greater(t, n, 0)

	data, err := os.ReadFile(filepath.Join(dir, "CRUSH.memory.md"))
	require.NoError(t, err)
	lines := strings.Split(string(data), "\n")
	require.LessOrEqual(t, len(lines), 51) // 50 lines + truncation marker
	require.Contains(t, string(data), "... (truncated)")
}

func TestWriteMemoryFile_ByteLimitEnforced(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	memories := []ExtractedMemory{
		{Type: MemoryFact, Content: strings.Repeat("x", 5000), Confidence: 0.9},
	}

	n, err := WriteMemoryFile(context.Background(), memories, dir, MemoryFileConfig{MaxChars: 100})
	require.NoError(t, err)
	require.LessOrEqual(t, n, 100)

	data, err := os.ReadFile(filepath.Join(dir, "CRUSH.memory.md"))
	require.NoError(t, err)
	require.LessOrEqual(t, len(data), 100)
}

func TestWriteMemoryFile_CustomPath(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	memories := []ExtractedMemory{
		{Type: MemoryFact, Content: "custom path test", Confidence: 0.9},
	}

	n, err := WriteMemoryFile(context.Background(), memories, dir, MemoryFileConfig{
		FilePath: "NOTES.memory.md",
	})
	require.NoError(t, err)
	require.Greater(t, n, 0)

	data, err := os.ReadFile(filepath.Join(dir, "NOTES.memory.md"))
	require.NoError(t, err)
	require.Contains(t, string(data), "custom path test")

	_, err = os.Stat(filepath.Join(dir, "CRUSH.memory.md"))
	require.True(t, os.IsNotExist(err))
}

func TestWriteMemoryFile_EmptyMemories(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()

	n, err := WriteMemoryFile(context.Background(), nil, dir, MemoryFileConfig{})
	require.NoError(t, err)
	require.Greater(t, n, 0)

	data, err := os.ReadFile(filepath.Join(dir, "CRUSH.memory.md"))
	require.NoError(t, err)
	content := string(data)
	require.Contains(t, content, "# Session Memory")
	require.Contains(t, content, "<!-- auto-generated by Crush -->")
}

func TestWriteMemoryFile_ManualMarkerSkips(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	existing := "# My Notes\n\n<!-- manual -->\n\nSome hand-written content.\n"
	require.NoError(t, os.WriteFile(filepath.Join(dir, "CRUSH.memory.md"), []byte(existing), 0o644))

	memories := []ExtractedMemory{
		{Type: MemoryFact, Content: "should not appear", Confidence: 0.9},
	}

	n, err := WriteMemoryFile(context.Background(), memories, dir, MemoryFileConfig{})
	require.NoError(t, err)
	require.Equal(t, 0, n)

	data, err := os.ReadFile(filepath.Join(dir, "CRUSH.memory.md"))
	require.NoError(t, err)
	require.Contains(t, string(data), "Some hand-written content")
	require.NotContains(t, string(data), "should not appear")
}

func TestShouldTrigger_AtInterval(t *testing.T) {
	t.Parallel()

	require.True(t, ShouldTrigger(5, MemoryTriggerConfig{MessageInterval: 5}))
	require.True(t, ShouldTrigger(10, MemoryTriggerConfig{MessageInterval: 5}))
	require.True(t, ShouldTrigger(3, MemoryTriggerConfig{MessageInterval: 3}))
}

func TestShouldTrigger_BelowInterval(t *testing.T) {
	t.Parallel()

	require.False(t, ShouldTrigger(0, MemoryTriggerConfig{MessageInterval: 5}))
	require.False(t, ShouldTrigger(3, MemoryTriggerConfig{MessageInterval: 5}))
	require.False(t, ShouldTrigger(4, MemoryTriggerConfig{MessageInterval: 5}))
}

func TestShouldTrigger_ZeroInterval_UsesDefault(t *testing.T) {
	t.Parallel()

	require.False(t, ShouldTrigger(4, MemoryTriggerConfig{}))
	require.True(t, ShouldTrigger(5, MemoryTriggerConfig{}))
	require.True(t, ShouldTrigger(6, MemoryTriggerConfig{MessageInterval: 0}))
	require.False(t, ShouldTrigger(2, MemoryTriggerConfig{MessageInterval: -1}))
}

func TestLoadMemoryFile_Missing(t *testing.T) {
	t.Parallel()

	_, err := LoadMemoryFile(t.TempDir())
	require.ErrorIs(t, err, os.ErrNotExist)
}

func TestLoadMemoryFile_RoundTrip(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	original := []ExtractedMemory{
		{Type: MemoryFact, Content: "The project uses SQLite via sqlc", Confidence: 0.95},
		{Type: MemoryDecision, Content: "Chose sha256 for ID generation", Confidence: 0.9},
		{Type: MemoryLesson, Content: "Tree-sitter requires CGO_ENABLED=1", Confidence: 0.85},
	}

	_, err := WriteMemoryFile(context.Background(), original, dir, MemoryFileConfig{})
	require.NoError(t, err)

	loaded, err := LoadMemoryFile(dir)
	require.NoError(t, err)
	require.Len(t, loaded, 3)

	require.Equal(t, MemoryFact, loaded[0].Type)
	require.Equal(t, "The project uses SQLite via sqlc", loaded[0].Content)
	require.InDelta(t, 0.5, loaded[0].Confidence, 0.01)

	require.Equal(t, MemoryDecision, loaded[1].Type)
	require.Equal(t, "Chose sha256 for ID generation", loaded[1].Content)

	require.Equal(t, MemoryLesson, loaded[2].Type)
	require.Equal(t, "Tree-sitter requires CGO_ENABLED=1", loaded[2].Content)
}

func TestLoadMemoryFile_ManualMarker(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	content := "# Notes\n\n<!-- manual -->\n\n- **[fact]** hand-written fact\n"
	require.NoError(t, os.WriteFile(filepath.Join(dir, "CRUSH.memory.md"), []byte(content), 0o644))

	loaded, err := LoadMemoryFile(dir)
	require.NoError(t, err)
	require.Empty(t, loaded)
}
