// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: map_runs.sql

package db

import (
	"context"
)

const getMapRun = `-- name: GetMapRun :one
SELECT run_id, session_id, status, input_path, output_path, schema_json, created_at, updated_at, tool_type FROM lcm_map_runs WHERE run_id = ?
`

func (q *Queries) GetMapRun(ctx context.Context, runID string) (LcmMapRun, error) {
	row := q.queryRow(ctx, q.getMapRunStmt, getMapRun, runID)
	var i LcmMapRun
	err := row.Scan(
		&i.RunID,
		&i.SessionID,
		&i.Status,
		&i.InputPath,
		&i.OutputPath,
		&i.SchemaJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ToolType,
	)
	return i, err
}

const getMapRunItems = `-- name: GetMapRunItems :many
SELECT item_id, run_id, status, input_json, output_json, error_msg, created_at, updated_at FROM lcm_map_items WHERE run_id = ? ORDER BY created_at ASC
`

func (q *Queries) GetMapRunItems(ctx context.Context, runID string) ([]LcmMapItem, error) {
	rows, err := q.query(ctx, q.getMapRunItemsStmt, getMapRunItems, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LcmMapItem{}
	for rows.Next() {
		var i LcmMapItem
		if err := rows.Scan(
			&i.ItemID,
			&i.RunID,
			&i.Status,
			&i.InputJson,
			&i.OutputJson,
			&i.ErrorMsg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMapRun = `-- name: InsertMapRun :exec
INSERT INTO lcm_map_runs (run_id, session_id, input_path, output_path, schema_json, tool_type)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertMapRunParams struct {
	RunID      string `json:"run_id"`
	SessionID  string `json:"session_id"`
	InputPath  string `json:"input_path"`
	OutputPath string `json:"output_path"`
	SchemaJson string `json:"schema_json"`
	ToolType   string `json:"tool_type"`
}

func (q *Queries) InsertMapRun(ctx context.Context, arg InsertMapRunParams) error {
	_, err := q.exec(ctx, q.insertMapRunStmt, insertMapRun,
		arg.RunID,
		arg.SessionID,
		arg.InputPath,
		arg.OutputPath,
		arg.SchemaJson,
		arg.ToolType,
	)
	return err
}

const updateMapRunStatus = `-- name: UpdateMapRunStatus :exec
UPDATE lcm_map_runs SET status = ?, updated_at = strftime('%s', 'now') WHERE run_id = ?
`

type UpdateMapRunStatusParams struct {
	Status string `json:"status"`
	RunID  string `json:"run_id"`
}

func (q *Queries) UpdateMapRunStatus(ctx context.Context, arg UpdateMapRunStatusParams) error {
	_, err := q.exec(ctx, q.updateMapRunStatusStmt, updateMapRunStatus, arg.Status, arg.RunID)
	return err
}
