// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_parts.sql

package db

import (
	"context"
)

const countMessagePartsBySession = `-- name: CountMessagePartsBySession :one
SELECT COUNT(*)
FROM message_parts
WHERE session_id = ?
`

func (q *Queries) CountMessagePartsBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.countMessagePartsBySessionStmt, countMessagePartsBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMessagePartsByMessageID = `-- name: DeleteMessagePartsByMessageID :exec
DELETE FROM message_parts
WHERE message_id = ?
`

func (q *Queries) DeleteMessagePartsByMessageID(ctx context.Context, messageID string) error {
	_, err := q.exec(ctx, q.deleteMessagePartsByMessageIDStmt, deleteMessagePartsByMessageID, messageID)
	return err
}

const getMessagePartsByMessageID = `-- name: GetMessagePartsByMessageID :many
SELECT part_id, message_id, session_id, part_type, part_index, content_json, created_at
FROM message_parts
WHERE message_id = ?
ORDER BY part_index ASC
`

func (q *Queries) GetMessagePartsByMessageID(ctx context.Context, messageID string) ([]MessagePart, error) {
	rows, err := q.query(ctx, q.getMessagePartsByMessageIDStmt, getMessagePartsByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagePart{}
	for rows.Next() {
		var i MessagePart
		if err := rows.Scan(
			&i.PartID,
			&i.MessageID,
			&i.SessionID,
			&i.PartType,
			&i.PartIndex,
			&i.ContentJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagePartsBySessionAndType = `-- name: GetMessagePartsBySessionAndType :many
SELECT part_id, message_id, session_id, part_type, part_index, content_json, created_at
FROM message_parts
WHERE session_id = ? AND part_type = ?
ORDER BY created_at ASC
`

type GetMessagePartsBySessionAndTypeParams struct {
	SessionID string `json:"session_id"`
	PartType  string `json:"part_type"`
}

func (q *Queries) GetMessagePartsBySessionAndType(ctx context.Context, arg GetMessagePartsBySessionAndTypeParams) ([]MessagePart, error) {
	rows, err := q.query(ctx, q.getMessagePartsBySessionAndTypeStmt, getMessagePartsBySessionAndType, arg.SessionID, arg.PartType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagePart{}
	for rows.Next() {
		var i MessagePart
		if err := rows.Scan(
			&i.PartID,
			&i.MessageID,
			&i.SessionID,
			&i.PartType,
			&i.PartIndex,
			&i.ContentJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessagePart = `-- name: InsertMessagePart :one
INSERT INTO message_parts (
    part_id,
    message_id,
    session_id,
    part_type,
    part_index,
    content_json
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING part_id, message_id, session_id, part_type, part_index, content_json, created_at
`

type InsertMessagePartParams struct {
	PartID      string `json:"part_id"`
	MessageID   string `json:"message_id"`
	SessionID   string `json:"session_id"`
	PartType    string `json:"part_type"`
	PartIndex   int64  `json:"part_index"`
	ContentJson string `json:"content_json"`
}

func (q *Queries) InsertMessagePart(ctx context.Context, arg InsertMessagePartParams) (MessagePart, error) {
	row := q.queryRow(ctx, q.insertMessagePartStmt, insertMessagePart,
		arg.PartID,
		arg.MessageID,
		arg.SessionID,
		arg.PartType,
		arg.PartIndex,
		arg.ContentJson,
	)
	var i MessagePart
	err := row.Scan(
		&i.PartID,
		&i.MessageID,
		&i.SessionID,
		&i.PartType,
		&i.PartIndex,
		&i.ContentJson,
		&i.CreatedAt,
	)
	return i, err
}
