// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type LcmContextItem struct {
	SessionID  string         `json:"session_id"`
	Position   int64          `json:"position"`
	ItemType   string         `json:"item_type"`
	MessageID  sql.NullString `json:"message_id"`
	SummaryID  sql.NullString `json:"summary_id"`
	TokenCount int64          `json:"token_count"`
}

type LcmLargeFile struct {
	FileID             string         `json:"file_id"`
	SessionID          string         `json:"session_id"`
	OriginalPath       string         `json:"original_path"`
	Content            sql.NullString `json:"content"`
	TokenCount         int64          `json:"token_count"`
	ExplorationSummary sql.NullString `json:"exploration_summary"`
	ExplorerUsed       sql.NullString `json:"explorer_used"`
	CreatedAt          int64          `json:"created_at"`
}

type LcmMapItem struct {
	ItemID     string         `json:"item_id"`
	RunID      string         `json:"run_id"`
	Status     string         `json:"status"`
	InputJson  string         `json:"input_json"`
	OutputJson sql.NullString `json:"output_json"`
	ErrorMsg   sql.NullString `json:"error_msg"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

type LcmMapRun struct {
	RunID      string `json:"run_id"`
	SessionID  string `json:"session_id"`
	Status     string `json:"status"`
	InputPath  string `json:"input_path"`
	OutputPath string `json:"output_path"`
	SchemaJson string `json:"schema_json"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type LcmSessionConfig struct {
	SessionID           string  `json:"session_id"`
	ModelName           string  `json:"model_name"`
	ModelCtxMaxTokens   int64   `json:"model_ctx_max_tokens"`
	CtxCutoffThreshold  float64 `json:"ctx_cutoff_threshold"`
	SoftThresholdTokens int64   `json:"soft_threshold_tokens"`
	HardThresholdTokens int64   `json:"hard_threshold_tokens"`
	CreatedAt           int64   `json:"created_at"`
	UpdatedAt           int64   `json:"updated_at"`
}

type LcmSummariesFt struct {
	Content string `json:"content"`
}

type LcmSummary struct {
	SummaryID  string `json:"summary_id"`
	SessionID  string `json:"session_id"`
	Kind       string `json:"kind"`
	Content    string `json:"content"`
	TokenCount int64  `json:"token_count"`
	FileIds    string `json:"file_ids"`
	CreatedAt  int64  `json:"created_at"`
}

type LcmSummaryMessage struct {
	SummaryID string `json:"summary_id"`
	MessageID string `json:"message_id"`
	Ord       int64  `json:"ord"`
}

type LcmSummaryParent struct {
	SummaryID       string `json:"summary_id"`
	ParentSummaryID string `json:"parent_summary_id"`
	Ord             int64  `json:"ord"`
}

type Message struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	Role             string         `json:"role"`
	Parts            string         `json:"parts"`
	Model            sql.NullString `json:"model"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	FinishedAt       sql.NullInt64  `json:"finished_at"`
	Provider         sql.NullString `json:"provider"`
	IsSummaryMessage int64          `json:"is_summary_message"`
	Seq              int64          `json:"seq"`
	TokenCount       int64          `json:"token_count"`
}

type MessagesFt struct {
	Content string `json:"content"`
}

type ReadFile struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	ReadAt    int64  `json:"read_at"`
}

type RepoMapFileCache struct {
	RepoKey  string `json:"repo_key"`
	RelPath  string `json:"rel_path"`
	Mtime    int64  `json:"mtime"`
	Language string `json:"language"`
	TagCount int64  `json:"tag_count"`
}

type RepoMapSessionRanking struct {
	RepoKey   string  `json:"repo_key"`
	SessionID string  `json:"session_id"`
	RelPath   string  `json:"rel_path"`
	Rank      float64 `json:"rank"`
}

type RepoMapSessionReadOnly struct {
	RepoKey   string `json:"repo_key"`
	SessionID string `json:"session_id"`
	RelPath   string `json:"rel_path"`
}

type RepoMapTag struct {
	ID       int64  `json:"id"`
	RepoKey  string `json:"repo_key"`
	RelPath  string `json:"rel_path"`
	Name     string `json:"name"`
	Kind     string `json:"kind"`
	NodeType string `json:"node_type"`
	Line     int64  `json:"line"`
	Language string `json:"language"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Todos            sql.NullString `json:"todos"`
}
