// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Snapshot file bridge
	AddSnapshotFile(ctx context.Context, arg AddSnapshotFileParams) error
	AppendLcmContextItem(ctx context.Context, arg AppendLcmContextItemParams) error
	ClearSessionSummaryMessageID(ctx context.Context, id string) error
	CloneSessionFiles(ctx context.Context, arg CloneSessionFilesParams) error
	// Fork operations
	CloneSessionMessages(ctx context.Context, arg CloneSessionMessagesParams) error
	CountTurnSnapshots(ctx context.Context, sessionID string) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Turn Snapshot CRUD
	CreateTurnSnapshot(ctx context.Context, arg CreateTurnSnapshotParams) (TurnSnapshot, error)
	DeleteAllLcmContextItems(ctx context.Context, sessionID string) error
	DeleteFile(ctx context.Context, id string) error
	DeleteLcmSummary(ctx context.Context, summaryID string) error
	DeleteLcmSummaryMessages(ctx context.Context, summaryID string) error
	DeleteLcmSummaryParents(ctx context.Context, summaryID string) error
	DeleteMessage(ctx context.Context, id string) error
	// Message operations for undo/rewind
	DeleteMessagesAfterSeq(ctx context.Context, arg DeleteMessagesAfterSeqParams) error
	DeleteOldTurnSnapshots(ctx context.Context, arg DeleteOldTurnSnapshotsParams) (int64, error)
	DeleteRepoMapFileCache(ctx context.Context, arg DeleteRepoMapFileCacheParams) error
	DeleteRepoMapTagsByPath(ctx context.Context, arg DeleteRepoMapTagsByPathParams) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	DeleteSessionRankings(ctx context.Context, arg DeleteSessionRankingsParams) error
	DeleteSessionReadOnlyPaths(ctx context.Context, arg DeleteSessionReadOnlyPathsParams) error
	DeleteSessionTurnSnapshots(ctx context.Context, sessionID string) error
	DeleteSnapshotFiles(ctx context.Context, snapshotID string) error
	DeleteSnapshotsAfterSeq(ctx context.Context, arg DeleteSnapshotsAfterSeqParams) error
	DeleteTurnSnapshot(ctx context.Context, id string) error
	GetAverageResponseTime(ctx context.Context) (int64, error)
	GetContentReplacement(ctx context.Context, id int64) (LcmContentReplacement, error)
	GetContentReplacementsByFileID(ctx context.Context, arg GetContentReplacementsByFileIDParams) ([]LcmContentReplacement, error)
	GetContentReplacementsBySessionPosition(ctx context.Context, arg GetContentReplacementsBySessionPositionParams) ([]LcmContentReplacement, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetFileWrite(ctx context.Context, arg GetFileWriteParams) (WrittenFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	GetLastSession(ctx context.Context) (Session, error)
	GetLatestTurnSnapshot(ctx context.Context, sessionID string) (TurnSnapshot, error)
	GetLatestUserMessage(ctx context.Context, sessionID string) (Message, error)
	GetLcmContextTokenCount(ctx context.Context, sessionID string) (interface{}, error)
	GetLcmLargeFile(ctx context.Context, fileID string) (LcmLargeFile, error)
	GetLcmSessionConfig(ctx context.Context, sessionID string) (LcmSessionConfig, error)
	GetLcmSummary(ctx context.Context, summaryID string) (LcmSummary, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetMessageBySessionAndSeq(ctx context.Context, arg GetMessageBySessionAndSeqParams) (Message, error)
	GetMessageCountByTimeRange(ctx context.Context, arg GetMessageCountByTimeRangeParams) (int64, error)
	GetMessagesByTimeRange(ctx context.Context, arg GetMessagesByTimeRangeParams) ([]Message, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetRepoMapFileCache(ctx context.Context, repoKey string) ([]RepoMapFileCache, error)
	GetRepoMapFileCacheByPath(ctx context.Context, arg GetRepoMapFileCacheByPathParams) (RepoMapFileCache, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	GetTurnSnapshot(ctx context.Context, id string) (TurnSnapshot, error)
	GetTurnSnapshotAtOrBeforeSeq(ctx context.Context, arg GetTurnSnapshotAtOrBeforeSeqParams) (TurnSnapshot, error)
	GetTurnSnapshotByMessage(ctx context.Context, arg GetTurnSnapshotByMessageParams) (TurnSnapshot, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	// LCM Context Items
	InsertLcmContextItem(ctx context.Context, arg InsertLcmContextItemParams) error
	// LCM Large Files
	InsertLcmLargeFile(ctx context.Context, arg InsertLcmLargeFileParams) error
	// LCM Map Items
	InsertLcmMapItem(ctx context.Context, arg InsertLcmMapItemParams) error
	// LCM Map Runs
	InsertLcmMapRun(ctx context.Context, arg InsertLcmMapRunParams) error
	// LCM Summaries
	InsertLcmSummary(ctx context.Context, arg InsertLcmSummaryParams) error
	// LCM Summary Messages
	InsertLcmSummaryMessage(ctx context.Context, arg InsertLcmSummaryMessageParams) error
	// LCM Summary Parents
	InsertLcmSummaryParent(ctx context.Context, arg InsertLcmSummaryParentParams) error
	InsertRepoMapTag(ctx context.Context, arg InsertRepoMapTagParams) error
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	ListContentReplacementsByRound(ctx context.Context, arg ListContentReplacementsByRoundParams) ([]LcmContentReplacement, error)
	ListContentReplacementsByState(ctx context.Context, arg ListContentReplacementsByStateParams) ([]LcmContentReplacement, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListLcmContextItems(ctx context.Context, sessionID string) ([]LcmContextItem, error)
	ListLcmLargeFilesBySession(ctx context.Context, sessionID string) ([]LcmLargeFile, error)
	ListLcmSummariesBySession(ctx context.Context, sessionID string) ([]LcmSummary, error)
	ListLcmSummaryMessages(ctx context.Context, summaryID string) ([]LcmSummaryMessage, error)
	ListLcmSummaryParents(ctx context.Context, summaryID string) ([]LcmSummaryParent, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListMessagesBySessionSeq(ctx context.Context, sessionID string) ([]Message, error)
	ListMessagesInSeqRange(ctx context.Context, arg ListMessagesInSeqRangeParams) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListRecentReadFiles(ctx context.Context, readAt int64) ([]ReadFile, error)
	ListRecentSessionReadFiles(ctx context.Context, arg ListRecentSessionReadFilesParams) ([]ReadFile, error)
	ListRepoMapDefsByName(ctx context.Context, arg ListRepoMapDefsByNameParams) ([]ListRepoMapDefsByNameRow, error)
	ListRepoMapTags(ctx context.Context, repoKey string) ([]ListRepoMapTagsRow, error)
	ListSessionRankings(ctx context.Context, arg ListSessionRankingsParams) ([]RepoMapSessionRanking, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessionReadOnlyPaths(ctx context.Context, arg ListSessionReadOnlyPathsParams) ([]string, error)
	ListSessionWrittenFiles(ctx context.Context, sessionID string) ([]WrittenFile, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListSnapshotFiles(ctx context.Context, snapshotID string) ([]ListSnapshotFilesRow, error)
	ListTurnSnapshotsBySession(ctx context.Context, sessionID string) ([]TurnSnapshot, error)
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	// LCM Content Replacements
	RecordContentReplacement(ctx context.Context, arg RecordContentReplacementParams) (int64, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	RecordFileWrite(ctx context.Context, arg RecordFileWriteParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	SearchLcmSummaries(ctx context.Context, arg SearchLcmSummariesParams) ([]SearchLcmSummariesRow, error)
	UpdateContentReplacementState(ctx context.Context, arg UpdateContentReplacementStateParams) error
	UpdateLcmLargeFileExploration(ctx context.Context, arg UpdateLcmLargeFileExplorationParams) error
	UpdateLcmMapItem(ctx context.Context, arg UpdateLcmMapItemParams) error
	UpdateLcmMapRunStatus(ctx context.Context, arg UpdateLcmMapRunStatusParams) error
	UpdateLcmSessionConfig(ctx context.Context, arg UpdateLcmSessionConfigParams) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateMessageTokenCount(ctx context.Context, arg UpdateMessageTokenCountParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
	// LCM Session Config
	UpsertLcmSessionConfig(ctx context.Context, arg UpsertLcmSessionConfigParams) error
	UpsertRepoMapFileCache(ctx context.Context, arg UpsertRepoMapFileCacheParams) error
	UpsertSessionRanking(ctx context.Context, arg UpsertSessionRankingParams) error
	UpsertSessionReadOnlyPath(ctx context.Context, arg UpsertSessionReadOnlyPathParams) error
}

var _ Querier = (*Queries)(nil)
