// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: turn_snapshots.sql

package db

import (
	"context"
)

const addSnapshotFile = `-- name: AddSnapshotFile :exec

INSERT INTO turn_snapshot_files (snapshot_id, file_id, path, version)
VALUES (?, ?, ?, ?)
ON CONFLICT(snapshot_id, path) DO UPDATE SET
    file_id = excluded.file_id,
    version = excluded.version
`

type AddSnapshotFileParams struct {
	SnapshotID string `json:"snapshot_id"`
	FileID     string `json:"file_id"`
	Path       string `json:"path"`
	Version    int64  `json:"version"`
}

// Snapshot file bridge
func (q *Queries) AddSnapshotFile(ctx context.Context, arg AddSnapshotFileParams) error {
	_, err := q.exec(ctx, q.addSnapshotFileStmt, addSnapshotFile,
		arg.SnapshotID,
		arg.FileID,
		arg.Path,
		arg.Version,
	)
	return err
}

const cloneSessionFiles = `-- name: CloneSessionFiles :exec
INSERT INTO files (
    id,
    session_id,
    path,
    content,
    version,
    created_at,
    updated_at
)
SELECT
    ? || f.id,
    ?,
    f.path,
    f.content,
    f.version,
    f.created_at,
    f.updated_at
FROM files f
WHERE f.session_id = ?
`

type CloneSessionFilesParams struct {
	ID          string `json:"id"`
	SessionID   string `json:"session_id"`
	SessionID_2 string `json:"session_id_2"`
}

func (q *Queries) CloneSessionFiles(ctx context.Context, arg CloneSessionFilesParams) error {
	_, err := q.exec(ctx, q.cloneSessionFilesStmt, cloneSessionFiles, arg.ID, arg.SessionID, arg.SessionID_2)
	return err
}

const cloneSessionMessages = `-- name: CloneSessionMessages :exec

INSERT INTO messages (
    id,
    session_id,
    role,
    parts,
    seq,
    model,
    provider,
    is_summary_message,
    token_count,
    created_at,
    updated_at
)
SELECT
    ? || m.id,
    ?,
    m.role,
    m.parts,
    (SELECT COALESCE(MAX(seq), 0) FROM messages sub WHERE sub.session_id = ?) + ROW_NUMBER() OVER (ORDER BY m.seq ASC),
    m.model,
    m.provider,
    m.is_summary_message,
    m.token_count,
    m.created_at,
    m.updated_at
FROM messages m
WHERE m.session_id = ?
ORDER BY m.seq ASC
`

type CloneSessionMessagesParams struct {
	ID          string `json:"id"`
	SessionID   string `json:"session_id"`
	SessionID_2 string `json:"session_id_2"`
	SessionID_3 string `json:"session_id_3"`
}

// Fork operations
func (q *Queries) CloneSessionMessages(ctx context.Context, arg CloneSessionMessagesParams) error {
	_, err := q.exec(ctx, q.cloneSessionMessagesStmt, cloneSessionMessages,
		arg.ID,
		arg.SessionID,
		arg.SessionID_2,
		arg.SessionID_3,
	)
	return err
}

const countTurnSnapshots = `-- name: CountTurnSnapshots :one
SELECT COUNT(*) FROM turn_snapshots
WHERE session_id = ?
`

func (q *Queries) CountTurnSnapshots(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.countTurnSnapshotsStmt, countTurnSnapshots, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTurnSnapshot = `-- name: CreateTurnSnapshot :one

INSERT INTO turn_snapshots (
    id,
    session_id,
    user_message_id,
    user_message_seq,
    created_at
) VALUES (
    ?, ?, ?, ?, strftime('%s', 'now')
)
RETURNING id, session_id, user_message_id, user_message_seq, created_at
`

type CreateTurnSnapshotParams struct {
	ID             string `json:"id"`
	SessionID      string `json:"session_id"`
	UserMessageID  string `json:"user_message_id"`
	UserMessageSeq int64  `json:"user_message_seq"`
}

// Turn Snapshot CRUD
func (q *Queries) CreateTurnSnapshot(ctx context.Context, arg CreateTurnSnapshotParams) (TurnSnapshot, error) {
	row := q.queryRow(ctx, q.createTurnSnapshotStmt, createTurnSnapshot,
		arg.ID,
		arg.SessionID,
		arg.UserMessageID,
		arg.UserMessageSeq,
	)
	var i TurnSnapshot
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.UserMessageSeq,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessagesAfterSeq = `-- name: DeleteMessagesAfterSeq :exec

DELETE FROM messages
WHERE session_id = ? AND seq > ?
`

type DeleteMessagesAfterSeqParams struct {
	SessionID string `json:"session_id"`
	Seq       int64  `json:"seq"`
}

// Message operations for undo/rewind
func (q *Queries) DeleteMessagesAfterSeq(ctx context.Context, arg DeleteMessagesAfterSeqParams) error {
	_, err := q.exec(ctx, q.deleteMessagesAfterSeqStmt, deleteMessagesAfterSeq, arg.SessionID, arg.Seq)
	return err
}

const deleteOldTurnSnapshots = `-- name: DeleteOldTurnSnapshots :execrows
DELETE FROM turn_snapshots
WHERE id IN (
    SELECT id FROM turn_snapshots AS ts_inner
    WHERE ts_inner.session_id = ?
    ORDER BY ts_inner.created_at ASC
    LIMIT (
        SELECT COUNT(*) - ? FROM turn_snapshots AS ts_count WHERE ts_count.session_id = ?
    )
)
`

type DeleteOldTurnSnapshotsParams struct {
	SessionID   string      `json:"session_id"`
	Column2     interface{} `json:"column_2"`
	SessionID_2 string      `json:"session_id_2"`
}

func (q *Queries) DeleteOldTurnSnapshots(ctx context.Context, arg DeleteOldTurnSnapshotsParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteOldTurnSnapshotsStmt, deleteOldTurnSnapshots, arg.SessionID, arg.Column2, arg.SessionID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionTurnSnapshots = `-- name: DeleteSessionTurnSnapshots :exec
DELETE FROM turn_snapshots
WHERE session_id = ?
`

func (q *Queries) DeleteSessionTurnSnapshots(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionTurnSnapshotsStmt, deleteSessionTurnSnapshots, sessionID)
	return err
}

const deleteSnapshotFiles = `-- name: DeleteSnapshotFiles :exec
DELETE FROM turn_snapshot_files
WHERE snapshot_id = ?
`

func (q *Queries) DeleteSnapshotFiles(ctx context.Context, snapshotID string) error {
	_, err := q.exec(ctx, q.deleteSnapshotFilesStmt, deleteSnapshotFiles, snapshotID)
	return err
}

const deleteSnapshotsAfterSeq = `-- name: DeleteSnapshotsAfterSeq :exec
DELETE FROM turn_snapshots
WHERE session_id = ? AND user_message_seq > ?
`

type DeleteSnapshotsAfterSeqParams struct {
	SessionID      string `json:"session_id"`
	UserMessageSeq int64  `json:"user_message_seq"`
}

func (q *Queries) DeleteSnapshotsAfterSeq(ctx context.Context, arg DeleteSnapshotsAfterSeqParams) error {
	_, err := q.exec(ctx, q.deleteSnapshotsAfterSeqStmt, deleteSnapshotsAfterSeq, arg.SessionID, arg.UserMessageSeq)
	return err
}

const deleteTurnSnapshot = `-- name: DeleteTurnSnapshot :exec
DELETE FROM turn_snapshots
WHERE id = ?
`

func (q *Queries) DeleteTurnSnapshot(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteTurnSnapshotStmt, deleteTurnSnapshot, id)
	return err
}

const getLatestTurnSnapshot = `-- name: GetLatestTurnSnapshot :one
SELECT id, session_id, user_message_id, user_message_seq, created_at FROM turn_snapshots
WHERE session_id = ?
ORDER BY user_message_seq DESC
LIMIT 1
`

func (q *Queries) GetLatestTurnSnapshot(ctx context.Context, sessionID string) (TurnSnapshot, error) {
	row := q.queryRow(ctx, q.getLatestTurnSnapshotStmt, getLatestTurnSnapshot, sessionID)
	var i TurnSnapshot
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.UserMessageSeq,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestUserMessage = `-- name: GetLatestUserMessage :one
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, seq, token_count, submitted_at, sent_to_llm_at, first_token_at, completed_at FROM messages
WHERE session_id = ? AND role = 'user'
ORDER BY seq DESC
LIMIT 1
`

func (q *Queries) GetLatestUserMessage(ctx context.Context, sessionID string) (Message, error) {
	row := q.queryRow(ctx, q.getLatestUserMessageStmt, getLatestUserMessage, sessionID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.Provider,
		&i.IsSummaryMessage,
		&i.Seq,
		&i.TokenCount,
		&i.SubmittedAt,
		&i.SentToLlmAt,
		&i.FirstTokenAt,
		&i.CompletedAt,
	)
	return i, err
}

const getMessageBySessionAndSeq = `-- name: GetMessageBySessionAndSeq :one
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, seq, token_count, submitted_at, sent_to_llm_at, first_token_at, completed_at FROM messages
WHERE session_id = ? AND seq = ? LIMIT 1
`

type GetMessageBySessionAndSeqParams struct {
	SessionID string `json:"session_id"`
	Seq       int64  `json:"seq"`
}

func (q *Queries) GetMessageBySessionAndSeq(ctx context.Context, arg GetMessageBySessionAndSeqParams) (Message, error) {
	row := q.queryRow(ctx, q.getMessageBySessionAndSeqStmt, getMessageBySessionAndSeq, arg.SessionID, arg.Seq)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.Provider,
		&i.IsSummaryMessage,
		&i.Seq,
		&i.TokenCount,
		&i.SubmittedAt,
		&i.SentToLlmAt,
		&i.FirstTokenAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTurnSnapshot = `-- name: GetTurnSnapshot :one
SELECT id, session_id, user_message_id, user_message_seq, created_at FROM turn_snapshots
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTurnSnapshot(ctx context.Context, id string) (TurnSnapshot, error) {
	row := q.queryRow(ctx, q.getTurnSnapshotStmt, getTurnSnapshot, id)
	var i TurnSnapshot
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.UserMessageSeq,
		&i.CreatedAt,
	)
	return i, err
}

const getTurnSnapshotAtOrBeforeSeq = `-- name: GetTurnSnapshotAtOrBeforeSeq :one
SELECT id, session_id, user_message_id, user_message_seq, created_at FROM turn_snapshots
WHERE session_id = ? AND user_message_seq <= ?
ORDER BY user_message_seq DESC
LIMIT 1
`

type GetTurnSnapshotAtOrBeforeSeqParams struct {
	SessionID      string `json:"session_id"`
	UserMessageSeq int64  `json:"user_message_seq"`
}

func (q *Queries) GetTurnSnapshotAtOrBeforeSeq(ctx context.Context, arg GetTurnSnapshotAtOrBeforeSeqParams) (TurnSnapshot, error) {
	row := q.queryRow(ctx, q.getTurnSnapshotAtOrBeforeSeqStmt, getTurnSnapshotAtOrBeforeSeq, arg.SessionID, arg.UserMessageSeq)
	var i TurnSnapshot
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.UserMessageSeq,
		&i.CreatedAt,
	)
	return i, err
}

const getTurnSnapshotByMessage = `-- name: GetTurnSnapshotByMessage :one
SELECT id, session_id, user_message_id, user_message_seq, created_at FROM turn_snapshots
WHERE session_id = ? AND user_message_seq = ? LIMIT 1
`

type GetTurnSnapshotByMessageParams struct {
	SessionID      string `json:"session_id"`
	UserMessageSeq int64  `json:"user_message_seq"`
}

func (q *Queries) GetTurnSnapshotByMessage(ctx context.Context, arg GetTurnSnapshotByMessageParams) (TurnSnapshot, error) {
	row := q.queryRow(ctx, q.getTurnSnapshotByMessageStmt, getTurnSnapshotByMessage, arg.SessionID, arg.UserMessageSeq)
	var i TurnSnapshot
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserMessageID,
		&i.UserMessageSeq,
		&i.CreatedAt,
	)
	return i, err
}

const listSnapshotFiles = `-- name: ListSnapshotFiles :many
SELECT tsf.snapshot_id, tsf.file_id, tsf.path, tsf.version, f.content
FROM turn_snapshot_files tsf
JOIN files f ON tsf.file_id = f.id
WHERE tsf.snapshot_id = ?
`

type ListSnapshotFilesRow struct {
	SnapshotID string `json:"snapshot_id"`
	FileID     string `json:"file_id"`
	Path       string `json:"path"`
	Version    int64  `json:"version"`
	Content    string `json:"content"`
}

func (q *Queries) ListSnapshotFiles(ctx context.Context, snapshotID string) ([]ListSnapshotFilesRow, error) {
	rows, err := q.query(ctx, q.listSnapshotFilesStmt, listSnapshotFiles, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnapshotFilesRow{}
	for rows.Next() {
		var i ListSnapshotFilesRow
		if err := rows.Scan(
			&i.SnapshotID,
			&i.FileID,
			&i.Path,
			&i.Version,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurnSnapshotsBySession = `-- name: ListTurnSnapshotsBySession :many
SELECT id, session_id, user_message_id, user_message_seq, created_at FROM turn_snapshots
WHERE session_id = ?
ORDER BY user_message_seq ASC
`

func (q *Queries) ListTurnSnapshotsBySession(ctx context.Context, sessionID string) ([]TurnSnapshot, error) {
	rows, err := q.query(ctx, q.listTurnSnapshotsBySessionStmt, listTurnSnapshotsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TurnSnapshot{}
	for rows.Next() {
		var i TurnSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserMessageID,
			&i.UserMessageSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
